// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"time"
)

type Transaction struct {
	ID        int64             `json:"id"`
	Metadata  map[string]string `json:"metadata"`
	Postings  []Posting         `json:"postings"`
	Reference *string           `json:"reference,omitempty"`
	Reverted  bool              `json:"reverted"`
	Timestamp time.Time         `json:"timestamp"`
}
