// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/formancehq/formance-sdk-go/pkg/models/shared"
	"net/http"
)

type GetTransactionRequest struct {
	Expand *string `queryParam:"style=form,explode=true,name=expand"`
	// Transaction ID.
	ID int64 `pathParam:"style=simple,explode=false,name=id"`
	// Name of the ledger.
	Ledger string `pathParam:"style=simple,explode=false,name=ledger"`
}

type GetTransactionResponse struct {
	ContentType string
	// Error
	ErrorResponse *shared.ErrorResponse
	// OK
	GetTransactionResponse *shared.GetTransactionResponse
	StatusCode             int
	RawResponse            *http.Response
}
